export const FETCH_USERS_START = 'adminsPage/FETCH_USERS_START';
export const FETCH_USERS_COMPLETE = 'adminsPage/FETCH_USERS_COMPLETE';

export const FETCH_ROLES_START = 'adminsPage/FETCH_ROLES_START';
export const FETCH_ROLES_COMPLETE = 'adminsPage/FETCH_ROLES_COMPLETE';

export const FETCH_CATEGORIES_START = 'adminsPage/FETCH_CATEGORIES_START';
export const FETCH_CATEGORIES_COMPLETE = 'adminsPage/FETCH_CATEGORIES_COMPLETE';

export const USER_FORM_ERROR = 'adminsPage/USER_FORM_ERROR';
export const CATEGORY_FORM_ERROR = 'adminsPage/CATEGORY_FORM_ERROR';

export const FETCH_UPDATED_USERS_ROW = 'adminsPage/FETCH_UPDATED_USERS_ROW';
export const FETCH_UPDATED_CATEGORIES_ROW = 'adminsPage/FETCH_UPDATED_CATEGORIES_ROW';
